services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: eZoom_fullstack_challenge
    volumes:
      - ./eZoom:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8091:80"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=db_eZoom
      - DB_USERNAME=db
      - DB_PASSWORD=password

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_eZoom
      MYSQL_USER: db
      MYSQL_PASSWORD: password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root

  composer:
    image: composer:latest
    container_name: composer
    working_dir: /app
    volumes:
      - ./eZoom:/app
    depends_on:
      - web

volumes:
  mysql_data: