services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: eZoom_fullstack_challenge
    volumes:
      - ./eZoom:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "8091:80"
      
  composer:
    image: composer:latest
    container_name: composer
    working_dir: /app
    volumes:
      - ./eZoom:/app
    depends_on:
      - web

volumes:
  mysql_data: