on:
  push:
    branches:
      - main

name: 🚀 Deploy Ezoom_laravel_fullstack 110% on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    environment: Ezoom_laravel_fullstack
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.SERVER_DIR }}
          local-dir: eZoom/